spring:
  application:
    name: "EMPLOYEE-MANAGEMENT"
  datasource:
    url: jdbc:postgresql://localhost/empdb?currentSchema=empschema
    username: postgres
    password: admin
  flyway:
    baseline-on-migrate: true
    schemas: empschema
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: false
    show_sql: true
